### ISSUE TITLE
Please add owned version, or remove lifetime from err

### ISSUE THREAD

**Issue by Chu-4hun** [knutwalker/lenient-semver#26]
This code provides lifetime err but really should not
```rust
let v = lenient_semver::Version::parse(version.as_str()).context("wrong version format")?;
let version = semver::Version::from(v);
```
```
error[E0597]: `version` does not live long enough
  --> lib/src/ecosystems/lua/rockcpec.rs:41:48
   |
36 |         let version = match VERSION_REGEX.captures(input) {
   |             ------- binding `version` declared here
...
41 |         let v = lenient_semver::Version::parse(version.as_str()).context("wrong version format")?;
   |                                                ^^^^^^^---------
   |                                                |
   |                                                borrowed value does not live long enough
   |                                                argument requires that `version` is borrowed for `'static`
...
79 |     }
   |     - `version` dropped here while still borrowed

```

Regular semver::Version doesnt require `static` lifetimes

```rust
let version = semver::Version::parse(version.as_str()).context("wrong version format")?;

```
this works fine

**Comment by Chu-4hun** [comment]
this part from readme doesnt work

version_semver

lenient_semver = { version = "*", features = [ "version_semver" ] }

If you need to store an owned copy of the version information, you should copy into semver::Version or your custom version type instead. If you only ever intend to store the version information, it might make more sense to parse directly into semver::Version instead.
```rust
use semver::Version;

let input = String::from("v1.3.3.7-beta-21+build-42");
let version = lenient_semver::Version::parse(&input).unwrap();
let version = Version::from(version);
assert_eq!("1.3.3-beta.21+7.build.42", &version.to_string());
```

**Comment by knutwalker** [comment]
Hi there

> This code provides lifetime err but really should not

`lenient_semver::Version` borrows from the input, the pre-release and build identifier components are references with the same lifetime as the input.

If you want to have an `'static`-ally lifetimed one, you can use [`disassociate_metadata`](https://docs.rs/lenient_version/0.4.2/lenient_version/struct.Version.html#method.disassociate_metadata).

Similarly, the error also borrows from the input and has an [`owned`](https://docs.rs/lenient_semver_parser/0.4.2/lenient_semver_parser/struct.Error.html#method.owned) method to create an owned version of it, which no longer borrows from the input.

> Regular semver::Version doesnt require `static` lifetimes

`lenient_semver::Version` is not (and was never meant to be) a drop-in replacement for `semver::Version`. If you wanna parse into `semver::Version`, but with the lenient rules from this parser, you can do so and just use `semver::Version`. This is actually the default behavior and ever since the 1.0 rewrite of `semver`, there is little need to use `lenient_semver::Version`, especially not if you _don't_ want to have it borrow from the input.


> this part from readme doesnt work

The doctest for it runs green, how does it not work? What sort of error are you getting?
